on:
  # Create branch > prettier / this workflows create commit on branch prettier.
  push:
    branches:
      - x_master
      
name : 'Prettier Plugin Jeedom'

jobs:
  prettier:
    uses: jeedom/workflows/.github/workflows/prettier.yml@main
